###
GET http://localhost:4000/pg

###
POST http://localhost:4000/pg/create_table

###
POST http://localhost:4000/pg/create_user
Content-Type: application/json

{ 
  "name": "Arijit", 
  "age": 24
}

###
GET http://localhost:4000/pg/users