###
GET http://localhost:4000/

###
POST http://localhost:4000/pg/create_table

###
POST http://localhost:4000/pg/create_user
Content-Type: application/json

{ 
  "name": "Arijit", 
  "age": 24
}

###
GET http://localhost:4000/pg/users



###
POST http://localhost:4000/mongo/create_collection

###
POST http://localhost:4000/mongo/create_user
Content-Type: application/json

{ 
  "name": "Arijit", 
  "age": 24
}

###
GET http://localhost:4000/mongo/users