
name: compose_server_2
services:
  db:
    container_name: db
    image: postgres:16.1-alpine3.19
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    restart: always
    ports:
      - 4000:5432

  app:
    container_name: app
    image: server_2:latest
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.server_2
    depends_on:
      - db
    ports:
      - 4001:4000

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    depends_on:
      - db
    ports:
      - 4002:80
