---

version: "3"

services:
  db:
    container_name: "server_2_db"
    image: postgres:16.1-alpine3.19
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432

  app:
    container_name: "server_2_app"
    image: server_2
    build:
      context: ./
      dockerfile: ./Dockerfile.server_2
    depends_on:
      - db
    ports:
      - 4001:4000
